# SPDX-License-Identifier: MIT

screen_w = 1920
screen_h = 1080
fullscreen = true
vsync = false
fps_max = 30
enable_sound = false
enable_clouds = false
enable_particles = false
enable_fog = true
enable_client_modding = true
show_debug = false
keymap_screenshot = KEY_F12
