bind_address = 192.168.0.24
port = 30001
server_announce = false
server_name = Voxel Boroughs Development
server_description = Private LAN development world
max_users = 4
enable_ipv6 = false
creative_mode = true
enable_damage = false
default_privs = interact,shout
disallow_empty_password = false
